"""empty message

Revision ID: a2a513cdbd60
Revises: 901b176ff058
Create Date: 2022-06-04 17:43:11.594779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a513cdbd60'
down_revision = '901b176ff058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=False))
    op.drop_column('Venue', 'venue_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('venue_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
